name: dataiku

on:
  push:
       branches: masteR

env: 
    CREATE_BUNDLE: test_${{ github.event.repository.updated_at}}
     

jobs:
  GenerateUniqueBundleName:
    name: Generate unique bundle name
    runs-on: ubuntu-latest
  
    steps:
      - name: Generate unique bundle name
        id: generate
        run: |
          echo ${{CREATE_BUNDLE}}
          
  
