name: dataiku

on:
  push:
       branches: master
       
     

jobs:
  GenerateUniqueBundleName:
    name: Generate unique bundle name
    runs-on: ubuntu-latest
    outputs:
      CREATE_BUNDLE: ${{ steps.generate.outputs.CREATE_BUNDLE }}
    steps:
      - name: Generate unique bundle name
        id: generate
        run: |
          CURRENT_DATETIME=$(date +%Y-%m-%d_%H-%m-%S)
          CREATE_BUNDLE="tenantA_${CURRENT_DATETIME}"
          echo "CREATE_BUNDLE=${CREATE_BUNDLE}"
          echo "::set-output name=CREATE_BUNDLE::${CREATE_BUNDLE}"
          
  EchoCreateBundleFromOtherJobs:
    name: Echo create bundle from other jobs
    needs: GenerateUniqueBundleName
    runs-on: ubuntu-latest
    steps:
      - name: Debug CREATE_BUNDLE in EchoCreateBundleFromOtherJobs
        run: echo "CREATE_BUNDLE=${{ needs.GenerateUniqueBundleName.outputs.CREATE_BUNDLE }}"
