name: dataiku

on:
  workflow_dispatch:
    inputs:
      adfsAccount:
        description: 'ADFS account'
        default: 'svc-dataiku-dev@dci.local'
      awsAccountID:
        required: true
        description: 'AWS account'
        default: '750115702482'
      tenant:
        type: choice
        required: true
        description: 'The tenant to update'
        options:
        - 'tenantA'
        - 'tenantB'
        - 'multi_projects'

env:
  CREATE_BUNDLE: ${{ inputs.tenant }}_${{ date +%Y-%m-%d_%H-%m-%S-%N }}

jobs:
  PrintCreateBundle:
    name: Print create bundle
    runs-on: ubuntu-latest

    steps:
      - name: Echo create bundle to file
        run: |
          # echo "${{ env.CREATE_BUNDLE }}" > create-bundle.txt
          echo "${{ env.CREATE_BUNDLE }}" 

  # PrintCreateBundleInNextJob:
  #   name: Print create bundle in next job
  #   needs: PrintCreateBundle
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Read create bundle from file
  #       run: |
  #         CREATE_BUNDLE=$(cat create-bundle.txt)

  #     - name: Print create bundle
  #       run: echo "Create bundle: ${{ CREATE_BUNDLE }}"
