name: Print Workflow Environment Variable

on:
  push:
    branches: [ master ]

env:
  MY_ENV_VAR: "This is a workflow environment variable."

jobs:
  print_env_var:
    runs-on: ubuntu-latest
    steps:
      - name: Print MY_ENV_VAR
        run: echo "${{ env.MY_ENV_VAR }}"
