name: Print Workflow Environment Variable with Current Time

on:
  push:
    branches: [ master ]

env:
  name_a: "test + $(date +%Y%m%d%H%M%S)"

jobs:
  print_env_var:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "${{ env.name_a }}"
          
  
