name: dataiku

on:
  push:
       branches: master

env: 
    CREATE_BUNDLE: "test + $(date +%Y%m%d%H%M%S)"
     

jobs:
  GenerateUniqueBundleName:
    name: Generate unique bundle name
    runs-on: ubuntu-latest
  
    steps:
      - name: Generate unique bundle name
        id: generate
        run: |
          "${{ env.CREATE_BUNDLE }}"
          
  
