name: dataiku

on:
  workflow_dispatch:
    inputs:
      adfsAccount:
        description: 'ADFS account'
        default: 'svc-dataiku-dev@dci.local'
      awsAccountID:
        required: true
        description: 'AWS account'
        default: '59896079094'
      tenant:
        type: choice
        required: true
        description: 'The tenant to update'
        options:
        - 'tenantA'
        - 'tenantB'
        - 'multi_projects'


jobs:
  GenerateUniqueBundleName:
    name: Generate unique bundle name
    runs-on: ubuntu-latest
    steps:
      - name: Generate unique bundle name
        run: |
          CURRENT_DATETIME=$(date +%Y-%m-%d_%H-%m-%S)
          CREATE_BUNDLE="tenantA_${CURRENT_DATETIME}"
          echo "CREATE_BUNDLE=${CREATE_BUNDLE}" >> $GITHUB_ENV

  EchoCreateBundleFromOtherJobs:
    name: Echo create bundle from other jobs
    needs: GenerateUniqueBundleName
    runs-on: ubuntu-latest
    steps:
      - name: Echo create bundle from other jobs
        run: |
           echo "Create bundle from other jobs: ${{ steps.previous-job.outputs.CREATE_BUNDLE }}"
