---
  name: Print Workflow Environment Variable with Current Time
  on:
    workflow_dispatch:
      inputs:
        tenant:
          type: choice
          required: true
          description: 'The tenant to update'
          options:
          - 'tenantA'

  env:
     CREATE_BUNDLE: ${{ inputs.tenant }}_$(date +%Y%m%d%H%M%S)

  jobs:
    bundle-creation:
      name: BundleCreation
      runs-on: ubuntu-latest
      

         
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: echo
          run: echo ${{ env.CREATE_BUNDLE }}
  
